import { NextRequest } from "next/server";
import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { authorize, ok, badRequest, notFound, auditFromCtx, notDeleted } from "@/lib/api-helpers";
const parseDate=(v:any)=>v?new Date(`${v}T00:00:00.000Z`):null;
async function nextNumber(tx:Prisma.TransactionClient){const y=new Date().getUTCFullYear();const c=await tx.decisionRefCounter.upsert({where:{prefix_year:{prefix:"DEC",year:y}},update:{nextNumber:{increment:1}},create:{prefix:"DEC",year:y,nextNumber:2}});return `DEC-${y}-${String(c.nextNumber-1).padStart(6,"0")}`;}
export async function GET(req:NextRequest){const a=await authorize("decisions","view");if(!a.ok)return a.response;const s=req.nextUrl.searchParams;const status=s.get("status");const search=s.get("search")?.trim();const where:any={...notDeleted(),...(status&&status!=="all"?{status}:{}),...(search?{OR:[{decisionNumber:{contains:search}},{title:{contains:search}},{description:{contains:search}}]}:{})};const items=await db.mDDecision.findMany({where,orderBy:{createdAt:"desc"},take:200});return ok({items});}
export async function POST(req:NextRequest){const a=await authorize("decisions","create");if(!a.ok)return a.response;let b:any;try{b=await req.json()}catch{return badRequest("Invalid JSON body.")}if(!String(b.title??"").trim())return badRequest("Decision title is required.");if(!["low","medium","high","critical"].includes(b.priority??"medium"))return badRequest("Invalid priority.");const d=await db.$transaction(async tx=>{const decisionNumber=await nextNumber(tx);return tx.mDDecision.create({data:{decisionNumber,title:String(b.title).trim(),description:b.description?String(b.description).trim():null,priority:b.priority??"medium",status:b.status??"draft",decisionDate:parseDate(b.decisionDate),dueDate:parseDate(b.dueDate),requestedById:a.ctx.userId,assignedToId:b.assignedToId||null,notes:b.notes||null}})});await auditFromCtx(a.ctx,{action:"create",module:"decisions",recordId:d.id,recordType:"MDDecision",description:`Created decision ${d.decisionNumber}`});return ok(d,201);}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const a=await authorize("decisions","edit");if(!a.ok)return a.response;const {id}=await params;const e=await db.mDDecision.findFirst({where:{id,...notDeleted()}});if(!e)return notFound("Decision not found.");let b:any;try{b=await req.json()}catch{return badRequest("Invalid JSON body.")}const data:any={};for(const k of ["title","description","priority","assignedToId","outcome","notes","status"])if(b[k]!==undefined)data[k]=b[k]||null;if(b.decisionDate!==undefined)data.decisionDate=parseDate(b.decisionDate);if(b.dueDate!==undefined)data.dueDate=parseDate(b.dueDate);const d=await db.mDDecision.update({where:{id},data});await auditFromCtx(a.ctx,{action:"update",module:"decisions",recordId:id,recordType:"MDDecision",description:`Updated decision ${d.decisionNumber}`});return ok(d);}
export async function DELETE(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const a=await authorize("decisions","delete");if(!a.ok)return a.response;const {id}=await params;const e=await db.mDDecision.findFirst({where:{id,...notDeleted()}});if(!e)return notFound("Decision not found.");await db.mDDecision.update({where:{id},data:{deletedAt:new Date()}});await auditFromCtx(a.ctx,{action:"delete",module:"decisions",recordId:id,recordType:"MDDecision",description:`Archived decision ${e.decisionNumber}`});return ok({id,archived:true});}