"use client";
import { useCallback,useEffect,useState } from "react";
import { Plus, Search, Check, X, Archive, Download, Upload, Loader2, FileText, Gavel, CheckCheck, Target } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/page-header";
import { EmptyState } from "@/components/common/empty-state";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { useAuth } from "@/hooks/use-auth";
import { formatMoney } from "@/lib/finance/money";

type Module = "documents"|"decisions"|"approvals"|"pipeline";
const config={
 documents:{title:"Documents",desc:"Securely register, upload and retrieve company documents.",icon:FileText},
 decisions:{title:"MD Decisions",desc:"Record, assign and track management decisions.",icon:Gavel},
 approvals:{title:"Approvals",desc:"Central approval queue for operational requests.",icon:CheckCheck},
 pipeline:{title:"Project Pipeline",desc:"Track opportunities from lead through closure.",icon:Target},
} as const;

function dateISO(v?:string|null){return v?v.slice(0,10):""}
function money(v:any){return formatMoney(String(v??0),"GHS")}

export function OperationalControlView({module}:{module:Module}){
 const {can}=useAuth(); const c=config[module]; const Icon=c.icon;
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all");
 const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [editing,setEditing]=useState<any|null>(null); const [file,setFile]=useState<File|null>(null);
 const blank:any=module==="documents"?{title:"",category:"General",description:"",externalUrl:""}:module==="decisions"?{title:"",description:"",priority:"medium",status:"draft",decisionDate:dateISO(new Date().toISOString()),dueDate:"",assignedToId:"",notes:""}:module==="approvals"?{title:"",description:"",entityType:"",entityId:"",approverId:""}:{title:"",description:"",stage:"lead",probability:"10",value:"0",currency:"GHS",expectedCloseDate:"",customerId:"",ownerId:"",source:"",notes:""};
 const [form,setForm]=useState<any>(blank);
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams();if(search)q.set("search",search);if(filter!=="all")q.set(module==="documents"?"category":"status",filter);if(module==="pipeline"&&filter!=="all"){q.delete("status");q.set("stage",filter)}const r=await fetch(`/api/${module}?${q}`,{cache:"no-store"});if(!r.ok)throw new Error("Unable to load.");const d=await r.json();setItems(d.items??[])}catch(e){toast.error(e instanceof Error?e.message:"Unable to load.")}finally{setLoading(false)}},[module,search,filter]);
 useEffect(()=>{load()},[load]);
 function startCreate(){setEditing(null);setForm(blank);setFile(null);setOpen(true)}
 function startEdit(x:any){setEditing(x);setFile(null);setForm(module==="documents"?{title:x.title,category:x.category,description:x.description??"",externalUrl:x.externalUrl??""}:module==="decisions"?{title:x.title,description:x.description??"",priority:x.priority,status:x.status,decisionDate:dateISO(x.decisionDate),dueDate:dateISO(x.dueDate),assignedToId:x.assignedToId??"",notes:x.notes??""}:{title:x.title,description:x.description??"",stage:x.stage,probability:String(x.probability),value:String(x.value),currency:x.currency,expectedCloseDate:dateISO(x.expectedCloseDate),customerId:x.customerId??"",ownerId:x.ownerId??"",source:x.source??"",notes:x.notes??""});setOpen(true)}
 async function save(){setSaving(true);try{let r:Response;if(module==="documents"&&!editing){const fd=new FormData();Object.entries(form).forEach(([k,v])=>v!==""&&fd.append(k,String(v)));if(file)fd.append("file",file);r=await fetch("/api/documents",{method:"POST",body:fd})}else{const payload=module==="documents"?form:module==="decisions"?form:module==="approvals"?form:{...form,probability:Number(form.probability),value:String(form.value||"0")};r=await fetch(editing?`/api/${module}/${editing.id}`:`/api/${module}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)})}if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||"Save failed.")}toast.success(editing?"Updated.":"Created.");setOpen(false);await load()}catch(e){toast.error(e instanceof Error?e.message:"Save failed.")}finally{setSaving(false)}}
 async function archive(x:any){if(!confirm(`Archive ${x.title||x.documentNumber||x.opportunityNumber}?`))return;const r=await fetch(`/api/${module}/${x.id}`,{method:"DELETE"});if(!r.ok){toast.error("Archive failed.");return}toast.success("Archived.");load()}
 async function approve(x:any,status:string){const r=await fetch(`/api/approvals/${x.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){const e=await r.json().catch(()=>({}));toast.error(e.error||"Action failed.");return}toast.success(status==="approved"?"Approved.":status==="rejected"?"Rejected.":"Cancelled.");load()}
 const filters=module==="documents"?["all","General","Finance","HR","Legal","Procurement","Project","Asset","Other"]:module==="decisions"?["all","draft","pending","approved","rejected","implemented","cancelled"]:module==="approvals"?["all","pending","approved","rejected","cancelled"]:["all","lead","qualified","proposal","negotiation","won","lost"];
 return <div className="space-y-5">
  <PageHeader title={c.title} description={c.desc} action={can(module,"create")?<Button onClick={startCreate}><Plus className="h-4 w-4"/> Add</Button>:null}/>
  <div className="flex flex-col gap-3 md:flex-row"><div className="flex-1"><Label>Search</Label><div className="relative mt-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…"/></div></div><div className="w-full md:w-56"><Label>{module==="documents"?"Category":"Status / Stage"}</Label><Select value={filter} onValueChange={setFilter}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{filters.map(x=><SelectItem key={x} value={x}>{x==="all"?"All":x.replace("_"," ")}</SelectItem>)}</SelectContent></Select></div></div>
  <div className="rounded-xl border bg-card">{loading?<div className="p-6 text-sm text-muted-foreground">Loading…</div>:items.length===0?<EmptyState icon={Icon} title={`No ${c.title.toLowerCase()} yet`} description={`Create your first record in ${c.title}.`} action={can(module,"create")?<Button onClick={startCreate}>Add</Button>:undefined}/>:<div className="overflow-x-auto"><Table><TableHeader><TableRow>{module==="documents"?<><TableHead>Document</TableHead><TableHead>Category</TableHead><TableHead>File</TableHead><TableHead>Created</TableHead></>:module==="decisions"?<><TableHead>Decision</TableHead><TableHead>Priority</TableHead><TableHead>Status</TableHead><TableHead>Due</TableHead></>:module==="approvals"?<><TableHead>Approval</TableHead><TableHead>Status</TableHead><TableHead>Requested</TableHead><TableHead>Action</TableHead></>:<><TableHead>Opportunity</TableHead><TableHead>Stage</TableHead><TableHead>Value</TableHead><TableHead>Probability</TableHead><TableHead>Close</TableHead></>}<TableHead/></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x.id}>
 {module==="documents"?<><TableCell><div className="font-medium">{x.title}</div><div className="text-xs text-muted-foreground">{x.documentNumber}</div></TableCell><TableCell>{x.category}</TableCell><TableCell>{x.fileName?<Button variant="link" className="h-auto p-0" onClick={()=>window.open(`/api/documents/${x.id}?download=1`,"_blank")}><Download className="mr-1 h-3 w-3"/>{x.fileName}</Button>:x.externalUrl?<a className="text-sm underline" href={x.externalUrl} target="_blank">External link</a>:"—"}</TableCell><TableCell>{dateISO(x.createdAt)}</TableCell></>:
 module==="decisions"?<><TableCell><div className="font-medium">{x.title}</div><div className="text-xs text-muted-foreground">{x.decisionNumber}</div></TableCell><TableCell><Badge variant="outline">{x.priority}</Badge></TableCell><TableCell><Badge>{x.status}</Badge></TableCell><TableCell>{dateISO(x.dueDate)||"—"}</TableCell></>:
 module==="approvals"?<><TableCell><div className="font-medium">{x.title}</div><div className="text-xs text-muted-foreground">{x.approvalNumber}</div></TableCell><TableCell><Badge variant="outline">{x.status}</Badge></TableCell><TableCell>{dateISO(x.requestedAt)}</TableCell><TableCell>{x.status==="pending"&&can(module,"approve")?<div className="flex gap-1"><Button size="sm" onClick={()=>approve(x,"approved")}><Check className="h-4 w-4"/></Button><Button size="sm" variant="destructive" onClick={()=>approve(x,"rejected")}><X className="h-4 w-4"/></Button></div>:"—"}</TableCell></>:
 <><TableCell><div className="font-medium">{x.title}</div><div className="text-xs text-muted-foreground">{x.opportunityNumber}</div></TableCell><TableCell><Badge variant="outline">{x.stage}</Badge></TableCell><TableCell>{money(x.value)}</TableCell><TableCell>{x.probability}%</TableCell><TableCell>{dateISO(x.expectedCloseDate)||"—"}</TableCell></>}
 <TableCell><div className="flex justify-end gap-1">{can(module,"edit")&&module!=="approvals"&&<Button variant="ghost" size="icon" onClick={()=>startEdit(x)} title="Edit">✎</Button>}{can(module,"delete")&&module!=="approvals"&&<Button variant="ghost" size="icon" onClick={()=>archive(x)} title="Archive"><Archive className="h-4 w-4"/></Button>}</div></TableCell>
 </TableRow>)}</TableBody></Table></div>}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing?"Edit":"Add"} {c.title.slice(0,-1)||c.title}</DialogTitle><DialogDescription>Keep operational records current and auditable.</DialogDescription></DialogHeader>
   <div className="grid gap-4 sm:grid-cols-2">
    <div className="sm:col-span-2"><Label>Title</Label><Input className="mt-1" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div>
    {module==="documents"&&<><div><Label>Category</Label><Input className="mt-1" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div><Label>File</Label><Input type="file" className="mt-1" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><div className="sm:col-span-2"><Label>External URL (optional)</Label><Input className="mt-1" value={form.externalUrl} onChange={e=>setForm({...form,externalUrl:e.target.value})}/></div></>}
    {module==="decisions"&&<><div><Label>Priority</Label><Select value={form.priority} onValueChange={v=>setForm({...form,priority:v})}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{["low","medium","high","critical"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Status</Label><Select value={form.status} onValueChange={v=>setForm({...form,status:v})}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{["draft","pending","approved","rejected","implemented","cancelled"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Decision Date</Label><Input type="date" className="mt-1" value={form.decisionDate} onChange={e=>setForm({...form,decisionDate:e.target.value})}/></div><div><Label>Due Date</Label><Input type="date" className="mt-1" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></div></>}
    {module==="approvals"&&<><div><Label>Entity Type</Label><Input className="mt-1" value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value})} placeholder="PurchaseOrder"/></div><div><Label>Entity ID</Label><Input className="mt-1" value={form.entityId} onChange={e=>setForm({...form,entityId:e.target.value})}/></div><div className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-1" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></>}
    {module==="pipeline"&&<><div><Label>Stage</Label><Select value={form.stage} onValueChange={v=>setForm({...form,stage:v})}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{["lead","qualified","proposal","negotiation","won","lost"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Probability %</Label><Input type="number" min="0" max="100" className="mt-1" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})}/></div><div><Label>Value</Label><Input className="mt-1" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></div><div><Label>Expected Close</Label><Input type="date" className="mt-1" value={form.expectedCloseDate} onChange={e=>setForm({...form,expectedCloseDate:e.target.value})}/></div><div><Label>Source</Label><Input className="mt-1" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></div></>}
    <div className="sm:col-span-2"><Label>Description / Notes</Label><Textarea className="mt-1" value={module==="approvals"?form.description:form.description??form.notes??""} onChange={e=>setForm({...form,description:e.target.value,notes:e.target.value})}/></div>
   </div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}{editing?"Save Changes":"Create"}</Button></DialogFooter>
  </Dialog>
 </div>
}