import { NextRequest } from "next/server";
import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { authorize, ok, badRequest, notFound, auditFromCtx, notDeleted } from "@/lib/api-helpers";
const parseDate=(v:any)=>v?new Date(`${v}T00:00:00.000Z`):null;
async function nextNumber(tx:Prisma.TransactionClient){const y=new Date().getUTCFullYear();const c=await tx.pipelineRefCounter.upsert({where:{prefix_year:{prefix:"OPP",year:y}},update:{nextNumber:{increment:1}},create:{prefix:"OPP",year:y,nextNumber:2}});return `OPP-${y}-${String(c.nextNumber-1).padStart(6,"0")}`;}
export async function GET(req:NextRequest){const a=await authorize("pipeline","view");if(!a.ok)return a.response;const s=req.nextUrl.searchParams;const stage=s.get("stage");const search=s.get("search")?.trim();const where:any={...notDeleted(),...(stage&&stage!=="all"?{stage}:{}),...(search?{OR:[{opportunityNumber:{contains:search}},{title:{contains:search}},{description:{contains:search}}]}:{})};const items=await db.pipelineOpportunity.findMany({where,orderBy:{createdAt:"desc"},take:200});return ok({items});}
export async function POST(req:NextRequest){const a=await authorize("pipeline","create");if(!a.ok)return a.response;let b:any;try{b=await req.json()}catch{return badRequest("Invalid JSON body.")}const title=String(b.title??"").trim();if(!title)return badRequest("Opportunity title is required.");const probability=Number(b.probability??10);if(!Number.isInteger(probability)||probability<0||probability>100)return badRequest("Probability must be between 0 and 100.");const value=Number(b.value??0);if(!Number.isFinite(value)||value<0)return badRequest("Value must be non-negative.");const o=await db.$transaction(async tx=>{const opportunityNumber=await nextNumber(tx);return tx.pipelineOpportunity.create({data:{opportunityNumber,title,description:b.description||null,customerId:b.customerId||null,stage:b.stage||"lead",probability,value,currency:b.currency||"GHS",expectedCloseDate:parseDate(b.expectedCloseDate),ownerId:b.ownerId||null,source:b.source||null,notes:b.notes||null,createdById:a.ctx.userId}})});await auditFromCtx(a.ctx,{action:"create",module:"pipeline",recordId:o.id,recordType:"PipelineOpportunity",description:`Created opportunity ${o.opportunityNumber}`});return ok(o,201);}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const a=await authorize("pipeline","edit");if(!a.ok)return a.response;const {id}=await params;const e=await db.pipelineOpportunity.findFirst({where:{id,...notDeleted()}});if(!e)return notFound("Opportunity not found.");let b:any;try{b=await req.json()}catch{return badRequest("Invalid JSON body.")}const data:any={};for(const k of ["title","description","customerId","stage","currency","ownerId","source","notes"])if(b[k]!==undefined)data[k]=b[k]||null;if(b.probability!==undefined){const p=Number(b.probability);if(!Number.isInteger(p)||p<0||p>100)return badRequest("Probability must be between 0 and 100.");data.probability=p;}if(b.value!==undefined){const v=Number(b.value);if(!Number.isFinite(v)||v<0)return badRequest("Value must be non-negative.");data.value=v;}if(b.expectedCloseDate!==undefined)data.expectedCloseDate=parseDate(b.expectedCloseDate);const o=await db.pipelineOpportunity.update({where:{id},data});await auditFromCtx(a.ctx,{action:"update",module:"pipeline",recordId:id,recordType:"PipelineOpportunity",description:`Updated opportunity ${o.opportunityNumber}`});return ok(o);}
export async function DELETE(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const a=await authorize("pipeline","delete");if(!a.ok)return a.response;const {id}=await params;const e=await db.pipelineOpportunity.findFirst({where:{id,...notDeleted()}});if(!e)return notFound("Opportunity not found.");await db.pipelineOpportunity.update({where:{id},data:{deletedAt:new Date()}});await auditFromCtx(a.ctx,{action:"delete",module:"pipeline",recordId:id,recordType:"PipelineOpportunity",description:`Archived opportunity ${e.opportunityNumber}`});return ok({id,archived:true});}