const BASE = "http://localhost:3000";
const csrfRes = await fetch(`${BASE}/api/auth/csrf`);
const csrfJson = await csrfRes.json();
const csrfCookies = (csrfRes as any).headers.getSetCookie?.() || [];
const csrfCookieStr = csrfCookies.map((c: string) => c.split(";")[0]).join("; ");
const body = new URLSearchParams({ email: "md@phase7.test", password: "TestPass123!", csrfToken: csrfJson.csrfToken, callbackUrl: "/", json: "true" });
const loginRes = await fetch(`${BASE}/api/auth/callback/credentials`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Cookie: csrfCookieStr }, body, redirect: "manual" });
const loginCookies = (loginRes as any).headers.getSetCookie?.() || [];
const cookie = loginCookies.map((c: string) => c.split(";")[0]).join("; ");
// Create invoice + add item
const invRes = await fetch(`${BASE}/api/sales/invoices`, { method: "POST", headers: { Cookie: cookie, "Content-Type": "application/json" }, body: JSON.stringify({ customerId: "cmtupavye00icnhwbf89leoig", dueDate: new Date(Date.now() + 86400000).toISOString() }) });
const inv = await invRes.json();
console.log("Invoice created:", inv.id, inv.invoiceNumber);
const itemRes = await fetch(`${BASE}/api/sales/invoices/${inv.id}/items`, { method: "POST", headers: { Cookie: cookie, "Content-Type": "application/json" }, body: JSON.stringify({ description: "Test", quantity: "10", unitPrice: "500.00", discount: "0", taxRate: "15" }) });
const itemData = await itemRes.json();
console.log("Item added:", itemRes.status);
const getRes = await fetch(`${BASE}/api/sales/invoices/${inv.id}`, { headers: { Cookie: cookie } });
const invData = await getRes.json();
console.log("subtotal:", invData.subtotal, typeof invData.subtotal);
console.log("tax:", invData.tax, typeof invData.tax);
console.log("total:", invData.total, typeof invData.total);
console.log("balanceDue:", invData.balanceDue, typeof invData.balanceDue);
